layout_spectrum: 0.3888342
color:
  saturation: 0.8561027
  lightness: 0.0111782
  brandStrength: 0.05706647
  rhythmicContrast: 0.7556625
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
typography_spectrum: 0.4721754
name: Be Real Creative
