collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8561027
  brandStrength: 0.05706647
  lightness: 0.8128162
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  rhythmicContrast: 0.7556625
typography_spectrum: 0.4721754
layout_spectrum: 0.6728499
name: Be Real Creative
